### ISSUE TITLE
Use nice Image Upload component for DAO and token creation

### ISSUE THREAD

**Issue by JakeHartnell** [DA0-DA0/dao-dao-ui#1012]
Want to move beyond this: 
![image](https://user-images.githubusercontent.com/521978/211943273-6a9a3aa0-2655-4a70-b10e-9e791b315471.png)

If we use the same component as with NFT creation the UX will be much nicer _and_ we'll have more images on IPFS. :heart: 

Related to #888

**Comment by NoahSaso** [comment]
Yesss great idea.
