### ISSUE TITLE
Logo doesn't immediately update upon executing an Action that updates the logo

### ISSUE THREAD

**Issue by elsehow** [DA0-DA0/dao-dao-ui#1036]
![image](https://user-images.githubusercontent.com/7132461/212751301-ded566ba-969b-4ab0-a0dd-3400b282dcec.png)

A DAO's logo doesn't immediately update after executing an Action that updates the logo. This is unexpected behavior, and may make users think the action didn't work.

**Comment by NoahSaso** [comment]
This is due to Next.js server caching. On proposal execution, we do immediately call the API endpoint that revalidates the page cache, it just takes some time to revalidate and propagate to its edge servers. I think there's nothing further we can do.

**Comment by elsehow** [comment]
Is there a way to invalidate the local cache, or hackily set the logo optimistically on the client side? If this is too much complexity/not worth it, feel free to close this issue with no further discussion.

**Comment by NoahSaso** [comment]
❤️
