### ISSUE TITLE
"Cast your vote" component still appears even governance proposal has been executed

### ISSUE THREAD

**Issue by elsehow** [DA0-DA0/dao-dao-ui#1038]
![image](https://user-images.githubusercontent.com/7132461/212795984-1984b223-26fb-4adf-9514-e8f4f22309f7.png)

After a governance proposal vote Action has been executed, members cannot vote on the proposal any longer. However, the component currently still displays the voting UI even after the proposal has been executed.

**Comment by NoahSaso** [comment]
This is actually on purpose, as a result of #957, to allow for people to express their opinion even when the vote has been finalized. Similar to how elections work in the US.
