### ISSUE TITLE
Inbox Usability Improvements

### ISSUE THREAD

**Issue by baoskee** [DA0-DA0/dao-dao-ui#1045]
Some people have been complaining about notifications not being cleared. They like having inbox zero.

Some ideas:
* Create read and unread state for each proposal notification
* Separate Followed DAOs from member DAOs. This just means separate notifications from participation (like on Github, you can be a Contributor and have notifications turned off or vice versa) 
* Create vote and not voted state for each proposal notification
* Create proposal passed and quorum reached state

**Comment by NoahSaso** [comment]
Added pending/read state in #1160
