### ISSUE TITLE
Update payroll vesting design

### ISSUE THREAD

**Issue by NoahSaso** [DA0-DA0/dao-dao-ui#1088]
WE GOT NEW DESIGNS FOR THE VESTING PAYROLL TAB 🎉🎉🎉

![image](https://user-images.githubusercontent.com/6721426/216797805-13d0a8fa-681e-4fff-8879-42d6d88d6782.png)
![image](https://user-images.githubusercontent.com/6721426/216797806-cf5bf01b-92d2-4b41-9fe1-58399ab780d9.png)

**Comment by 0xekez** [comment]
LETS FUCKING GOOOOOOO @modern-edamame
