### ISSUE TITLE
DAO DAO Timeout Error when Minting NFTs

### ISSUE THREAD

**Issue by ShayneRarma** [DA0-DA0/dao-dao-ui#1101]
**Issue:** 
DAO DAO Timeout Error when Minting NFTs

**Steps to Reproduce:**
When minting NFTs via proposal on DAO DAO
Attempt to mint more than 8 NFTs in one proposal
Observed DAO DAO performance issues leading to the timeout error page

**Expected Result:**
The user should be able to mint as many NFTs as desired (within reason) without encountering a timeout or error page.

**Actual Result:**
DAO DAO times out and an error page is displayed when attempting to mint more than 8 NFTs, or if the page is left open for too long.
![image](https://user-images.githubusercontent.com/34254288/217720806-507aefcb-be36-4f91-b74f-466958fe9b92.png)

**Comment by JakeHartnell** [comment]
Is this still an issue?

**Comment by NoahSaso** [comment]
Closing because I do not think this is an issue anymore.
