### ISSUE TITLE
Improve functionality of "Load More" button for reviewing proposals

### ISSUE THREAD

**Issue by ShayneRarma** [DA0-DA0/dao-dao-ui#1102]
**Suggestion:**
Improve functionality of "Load More" Button for Reviewing Proposals

**Steps to Reproduce:**
Go to the proposals page
Scroll down to the bottom of the page, below the closed proposals
Use the "Load More" button
Additional "active" proposals will appear, as well as more closed proposals

**Expected Result:**
The "Load More" button should be split into two separate buttons, one for loading more open proposals and one for loading more closed proposals.

**Actual Result:**
The "Load More" button loads both open and closed proposals, making it difficult to review large lists of proposals.

![image](https://user-images.githubusercontent.com/34254288/217732875-f41585ae-3bb9-4f5c-bee2-99f8dbb0b7b4.png)
![image](https://user-images.githubusercontent.com/34254288/217732913-d2299a0a-b66d-40b9-b7eb-5381884da3f5.png)

**Comment by NoahSaso** [comment]
We can't request only open or only not-open proposals from the contract, so we just have to load the next `X` proposals and see what happens. That being said, a recent change I made loads 100 at a time instead of 20, which should significantly help out here. Good enough for now IMO.
