### ISSUE TITLE
Error in AuthZ Execution for SubDAO Proposals

### ISSUE THREAD

**Issue by ShayneRarma** [DA0-DA0/dao-dao-ui#1104]
**Issue:** 
Error in AuthZ Execution for SubDAO Proposals

**Steps to Reproduce:**
Go to a subDAO with AuthZ access to a DAO's treasury
Submit a proposal to use AuthZ Exec
Observe the error "Simulation failed"
Submit the proposal despite the error
Executive the Proposal and observe the failure of the proposal to fulfill the AuthZ request - Example: https://daodao.zone/dao/juno18mvc8kr64vvfywn8whmtsegsk6pzea9tqv6zfd20uj5jjm0xuh7sknj4z6/proposals/A29

**Expected Result:**
The proposal should successfully fulfill the AuthZ request and transfer funds from the DAO's treasury to the subDAO.

**Actual Result:**
An error "Simulation failed" is displayed, and the proposal fails to fulfill the AuthZ request even if submitted.
![image](https://user-images.githubusercontent.com/34254288/217769103-27ea69a5-1dfc-4c19-a5a8-2f57fb548d76.png)
![image](https://user-images.githubusercontent.com/34254288/217768472-113b5aa2-a77c-4f5d-adbe-1b3f34f1cf67.png)

**Comment by NoahSaso** [comment]
Closed by #1180
