### ISSUE TITLE
Support non-transferrable tokens for DAOs

### ISSUE THREAD

**Issue by JakeHartnell** [DA0-DA0/dao-dao-ui#1130]
@ekez and I talked with some people want to have a DAO with non-transferable tokens or NFTs. This should be an option when creating a DAO.

**Comment by NoahSaso** [comment]
Isn't this more of a dao-contracts issue? As long as the API is the same as current NFT staking, it will all work right away. If this is a new type of voting module, then we'll have to build an adapter.

**Comment by 0xekez** [comment]
i think this is two pronged, (1) a non-transferable code ID, (2) UI support to toggle using it.

on the contracts side we'll need to construct a token contract that can only be transferred to/from the staking contract.

**Comment by JakeHartnell** [comment]
Supported in contracts now, so this can finally be an option (at least for tokens).

However, probably best to close this and make a milestone for the new Token Factory and NFT DAOs that are supported by DAO DAO v2.3.
