### ISSUE TITLE
Inability to Execute Smart Contract with Both Native and CW20 Tokens in Same Transaction

### ISSUE THREAD

**Issue by ShayneRarma** [DA0-DA0/dao-dao-ui#1146]
**Issue:** 
Inability to Execute Smart Contract with Both Native and CW20 Tokens in Same Transaction

**Steps to Reproduce:**
Attempt to execute a smart contract that involves both native tokens and CW20 tokens in the same transaction
Notice that only one type of token can be used in the transaction

**Expected Result:**
The ability to execute smart contracts that involve both native tokens and CW20 tokens in the same transaction, in order to provide liquidity to pools.

**Actual Result:**
Currently, users are only able to use one type of token in a smart contract transaction, either native tokens or CW20 tokens. This limits the ability to provide liquidity to pools, as both types of tokens are often needed.
![image](https://user-images.githubusercontent.com/34254288/221388452-550bbdf4-bab4-4e34-aa92-35c1477ef3bb.png)
![image](https://user-images.githubusercontent.com/34254288/221388455-cc77d871-278c-43ea-94a9-d88cf09cab88.png)

**Comment by NoahSaso** [comment]
I don't think this is possible. CW20 and native tokens are sent in different ways, and the CW20 contract token send message doesn't pass native token payments through (as far as I know).

When you go to provide liquidity on WYND, it instead executes two messages:

On the cw20 token:
```
{
  "increase_allowance": {
    "amount": "<CW20_AMOUNT>",
    "spender": "<POOL_CONTRACT>"
  }
}
```

On the pool, with the native funds sent along with this message:
```
{
  "provide_liquidity": {
    "assets": [
      {
        "amount": "<CW20_AMOUNT>",
        "info": {
          "token": "<CW20_CONTRACT>"
        }
      },
      {
        "amount": "<NATIVE_AMOUNT>",
        "info": {
          "native": "ujuno"
        }
      }
    ],
    "slippage_tolerance": "0.03"
  }
}
```

This gives the pool permission to spend up to `CW20_AMOUNT` of your tokens on your behalf.
