### ISSUE TITLE
Enable HSTS preload

### ISSUE THREAD

**Issue by elsehow** [DA0-DA0/dao-dao-ui#1168]
HSTS preload prevents MITM attacks by ensuring users can *only* access DAO DAO over HTTP. This is important because a financially motivated attacker may poison DNS, ship a MITM'd DAO DAO app, and do bad things.

This should be [an easy enough Next.js configuration change](https://www.beskar.co/blog/next-hsts-preload).

**Comment by webmaster128** [comment]
Vercel seems to do this by default server-side. See https://vercel.com/docs/concepts/edge-network/headers#strict-transport-security and

```
$ curl -sS --head https://daodao.zone | grep strict-transport-security
strict-transport-security: max-age=63072000
```
