### ISSUE TITLE
Fee Share Action

### ISSUE THREAD

**Issue by JakeHartnell** [DA0-DA0/dao-dao-ui#1177]
Fee Share is awesome, and DAOs / individuals are going to want to use it.

**Comment by Reecepbcups** [comment]
Really rough example: https://github.com/Reecepbcups/juno-feeshare-webapp

(Since it requires custom proto signing)

**Comment by JakeHartnell** [comment]
Ah, looks like the proto has landed in `juno-ts`: https://github.com/CosmosContracts/juno-ts/pull/5
