### ISSUE TITLE
Enhancement: "Vote on DAO Proposal" action

### ISSUE THREAD

**Issue by ShayneRarma** [DA0-DA0/dao-dao-ui#1197]
As a DAO when you stake another DAOs token, it would be nice to have an Action to vote on their open proposals. Rather than having to use execute smart contract custom action

![image](https://user-images.githubusercontent.com/34254288/228116048-76ecf3e2-9003-4a67-a241-df97898d288f.png)
![image](https://user-images.githubusercontent.com/34254288/228116075-993f639b-9da2-4dfe-bce0-63ff975ac6de.png)

**Comment by JakeHartnell** [comment]
Will be tackled in #1425!
