### ISSUE TITLE
Issue: Inability to Add Both Payroll and Retroactive Payments as Payment Options for DAO

### ISSUE THREAD

**Issue by ShayneRarma** [DA0-DA0/dao-dao-ui#1199]
Steps to Reproduce:

Add payroll and retroactive payments as payment options for a DAO
Notice that only one widget is available for these payment options
Attempt to add both payment options as separate widgets
Expected Result:
The ability to add both payroll and retroactive payments as separate payment options for a DAO using separate widgets.

Actual Result:
Only one widget is available for adding payroll and retroactive payments as payment options for a DAO. This limits the ability to use both payment options in the same DAO.

Can verify in Rarma DAO - https://daodao.zone/dao/juno1nvfw3xesfz5s8k8l85kuwra5dcryzheu4nq2m2yfe79l9tc0zx9sju5acm

**Comment by NoahSaso** [comment]
Closed by #1207
