### ISSUE TITLE
Documentation: DAO DAO Spend Type Actions - CSV Format Guide

### ISSUE THREAD

**Issue by ShayneRarma** [DA0-DA0/dao-dao-ui#1205]
To bulk load "spend" type actions into a DAO DAO Proposal, you need to provide a CSV file with the following format:

`spend,"WALLET_ADDRESS","AMOUNT","TOKEN_DENOM/CONTRACT_ADDRESS"`

**Columns Explanation:**
Action Type: In this case, "spend" is the action type. This column must always contain the keyword "spend" for each entry.

**Wallet Address:** A string containing the user's wallet address who will receive the spend action. The wallet address should be enclosed in triple double quotes, e.g., """juno10123abc""".

**Amount:** A string containing the amount of tokens to be spent. The amount should be represented as an integer and enclosed in triple double quotes, e.g., """1""" (1 JUNO).

**Token Denom or Contract address:** A string containing the symbol of the token to be spent. The token symbol should be in lowercase and enclosed in triple double quotes, e.g., """ujuno""" (Juno) or """juno1wfsrzyqz6quuzenf4c3uagmrp6mds33s94qeknaxhcyxatr9r2ds4k07av""" (CORP).

Example:
Here's an example of a single spend action in the required CSV format:

`spend,"""juno10a29hu7chl55ar4wsyjueqxc7smudpvrs3rjam""","""1""","""ujuno"""`

**Notes:**
When creating the CSV file, make sure to use a plain text editor or a CSV editor to avoid formatting issues.
Each line in the CSV file represents one spend action entry. If you want to add multiple spend actions, simply add a new line for each action, following the same format.
Ensure that the wallet addresses, amounts, and token denom or contract address are accurate and valid, as incorrect data may result in inaccurate actions.
You will be able to review the imported data before the Actions are created, after the actions are generated, and before submitting the Proposal for voting.

**Comment by NoahSaso** [comment]
This has been replaced by the JSON format, found in [this guide](https://github.com/DA0-DA0/dao-dao-ui/wiki/Bulk-importing-actions). Thank you for writing this up and helping troubleshoot it!
