### ISSUE TITLE
Enable < > & in proposal title

### ISSUE THREAD

**Issue by elsehow** [DA0-DA0/dao-dao-ui#1239]
Currently, if the proposal title has some special characters in the title, creating the proposal will fail. I understand this stems from issues with the Cosmos SDK, but perhaps we could apply some frontend magic to make this possible for users. 

For example, could we encode these characters with their Unicode equivalents, e.g. `U+00026`?

**Comment by NoahSaso** [comment]
This is a Keplr issue actually, and they merged in my PR that fixed it some weeks ago. Not sure when it'll be fixed in the extension, but it's on its way!
