### ISSUE TITLE
Put Manage Staking action in Blockchain Governance Action Pack

### ISSUE THREAD

**Issue by elsehow** [DA0-DA0/dao-dao-ui#1241]
It's unexpected (to me) that Manage Staking is under the DAO Treasury Action Pack instead of Blockchain Governance. While I understand staking happens from tokens in the treasury, Blockchain Governance seems to be the more specific category that relates to this action.

**Comment by JakeHartnell** [comment]
Closing this for now, probably do need to take another pass soon at action pack organization.
