### ISSUE TITLE
Clicking a DAO should open in the same tab

### ISSUE THREAD

**Issue by elsehow** [DA0-DA0/dao-dao-ui#1310]
Currently, clicking on a DAO in an inline link will open the link a different tab:

![image](https://github.com/DA0-DA0/dao-dao-ui/assets/7132461/2a3f71ee-115f-442a-80f7-100841d01c1f)

I think in-bound links should rarely if ever open in new tabs; regular navigation rules within the app should always navigate to the new page in the same tab.

If the intention here is to prevent the user from navigating away while editing, we might want to address that with a confirmation modal instead.

**Comment by rishav-karanjit** [comment]
Hi @elsehow and @JakeHartnell, is this issue solved? Can I work on this issue. I am not able to view the image on the description

**Comment by JakeHartnell** [comment]
@rishav-karanjit, it's still open. Go for it!

**Comment by rishav-karanjit** [comment]
@JakeHartnell, What link is this issue taking about?

**Comment by rishav-karanjit** [comment]
Do you mean the arrow on top right (with info view DAO's page) of the middle column? @elsehow @JakeHartnell 

https://daodao.zone/dao/juno10h0hc64jv006rr8qy0zhlu4jsxct8qwa0vtaleayh0ujz0zynf2s2r7v8q/proposals

**Comment by NoahSaso** [comment]
No, this refers to the `EntityDisplay` component in `packages/stateless/components/EntityDisplay.tsx`. It uses a `ButtonLink` with `openInNewTab` always enabled.

Ideally, add an optional `openInNewTab` flag to `EntityDisplayProps` in `packages/types/stateless/EntityDisplay.tsx`, and default it to `false` in the component (just like `size`). Then just pass it through to the `ButtonLink` directly.

**Comment by rishav-karanjit** [comment]
Just created a new PR.
