### ISSUE TITLE
Option to only pay the minimum required amount for a proposal deposit

### ISSUE THREAD

**Issue by JakeHartnell** [DA0-DA0/dao-dao-ui#1393]
Currently, when you make an on-chain prop for Osmosis, Stargaze, or Juno, the proposer has to pay the full proposal deposit. Not everyone is able to afford this and had a few people reach out about an option to pay the minimum deposit.

**Comment by NoahSaso** [comment]
I'm pretty sure it defaults to the full deposit but it'll let you submit the minimum deposit if you change the number. Can you check again? I did that on purpose.

**Comment by JakeHartnell** [comment]
You are right! Closing...
