### ISSUE TITLE
Remove price from claimed balance line of vesting payment

### ISSUE THREAD

**Issue by NoahSaso** [DA0-DA0/dao-dao-ui#1445]
Once funds are claimed, the price displayed is misleading because it always uses the current price. I think we can just hide the price for the claimed balance.

**Comment by rishav-karanjit** [comment]
Hi @NoahSaso, I was wondering if I can get few more details on this issue?

**Comment by NoahSaso** [comment]
> Hi @NoahSaso, I was wondering if I can get few more details on this issue?

Yep! This "Claimed balance" line in the vesting payment card is misleading:
![image](https://github.com/DA0-DA0/dao-dao-ui/assets/6721426/26fecc62-9a0b-4cce-ba4a-a8f28504d198)

**Comment by rishav-karanjit** [comment]
Hello @NoahSaso, after heavy search I found this code [here](https://github.com/DA0-DA0/dao-dao-ui/blob/development/packages/stateful/widgets/widgets/VestingPayments/components/VestingPaymentCard/VestingPaymentCard.tsx#L486-L523). Is this the code related to the issue? If not, could you point me to the file related to this issue?

**Comment by NoahSaso** [comment]
Yes that's it! I think all you need to do is delete the price display piece :)

**Comment by rishav-karanjit** [comment]
I have create a PR, @NoahSaso.

**Comment by rishav-karanjit** [comment]
@NoahSaso I updated the PR by just removed the USD price
