### ISSUE TITLE
No way to navigate to chain-specific home page

### ISSUE THREAD

**Issue by NoahSaso** [DA0-DA0/dao-dao-ui#1489]
The home page that shows feed, featured, and followed DAOs shows DAOs on all chains. Each supported chain also has its own page (e.g. `/stargaze`) that only shows featured and followed DAOs from that chain, but there's no way to navigate to these pages without knowing they exist and manually typing them into the browser.

One way to solve this would be to add a chain switcher to the home page with an extra `All Chains` option that is selected by default on the main home page.

**Comment by JakeHartnell** [comment]
> One way to solve this would be to add a chain switcher to the home page with an extra All Chains option that is selected by default on the main home page.

Great improvement.
