### ISSUE TITLE
Easier to find staking button

### ISSUE THREAD

**Issue by JakeHartnell** [DA0-DA0/dao-dao-ui#1524]
Sunny and others have suggested relocating the staking button to a place that’s more obvious (especially on mobile).

https://x.com/cosmosjunky2/status/1736136812471472424?s=46

**Comment by NoahSaso** [comment]
so true. will get on this

**Comment by JakeHartnell** [comment]
Maybe deserves it's own tab.

**Comment by NoahSaso** [comment]
what if we show the home page for all DAOs and put it at the top. proposals can be the second tab? i think the home page will inspire more customization too.

**Comment by JakeHartnell** [comment]
Let's iterate, try things, and get feedback. :shipit:

**Comment by Trigs-0** [comment]
There is often confusion depending on your screen size on desktop, as well. Smaller screens have to click the little button at the button right to login or see the side panel. It's not obvious at first. I have to tell ppl to look for it every so often when we get a new staker.

Something more persistent maybe. Looking forward to what ideas you come up with to try.

**Comment by NoahSaso** [comment]
<img width="1140" alt="Screenshot 2023-12-16 at 14 09 43" src="https://github.com/DA0-DA0/dao-dao-ui/assets/6721426/0c8a46a1-6ea5-45a0-8f2b-6c09ee5f0228">

@JakeHartnell @Trigs-0 thoughts?

**Comment by Trigs-0** [comment]
I like it much better! I bet it looks good on mobile too.

It might just be me but I also feel like the login/sidepanel button should be top right instead of bottom right? Seems more industry standard. I always look for it there. Less of an issue with the staking update displayed here, but still relevant I feel.
