### ISSUE TITLE
UX improvement ideas

### ISSUE THREAD

**Issue by NoahSaso** [DA0-DA0/dao-dao-ui#1534]
We should enhance the UX, especially on mobile. Some thoughts from Twitter space:

- No need to load all proposals at once. Infinite scroll when proposal line becomes visible?
- Redesign treasuries with multi-chain in mind. Don't need to load all at once. Must wait for all to load to scroll down to the one you want. There should probably just be a switcher at the top.
- DAO home page complete redesign for mobile, tab selection, closer to v1 design probably.
- Proposal page should be totally redesigned for mobile. It's way too tall and one long column of various information is not intuitive nor helpful.

**Comment by noahsaso** [comment]
done :)
