### ISSUE TITLE
Veto Support for x/gov Chain Governance

### ISSUE THREAD

**Issue by JakeHartnell** [DA0-DA0/dao-dao-ui#1543]
As a chain, I want to have a SubDAO that the wider community has veto ability over. For example, the Juno Community has veto over the Council in the [Juno Charter](https://hackmd.io/@G2q75faESMyRkexdnhUCpA/B1NPVxxRh).

Would be nice to see props able to be vetoed, and make sure tho veto action works.

Test DAO and prop on Juno Testnet (with Juno gov module as vetoer): https://dapp-testnet-git-noah-v240-da0da0.vercel.app/dao/juno19fyrul7gfcawd60m45ws4m2mlcczq6jza4w3qem7d4v9pxgjcxmq7xv0h2/proposals/A1

**Comment by NoahSaso** [comment]
Fixed in https://github.com/DA0-DA0/dao-dao-ui/pull/1537/commits/3bb9fa87483e0f3c0fd09ff23a8f9195f808e501
