### ISSUE TITLE
Veto / Approval configuration UI Cleanup

### ISSUE THREAD

**Issue by JakeHartnell** [DA0-DA0/dao-dao-ui#1544]
Long DAO name throws off formatting on review page:

![image](https://github.com/DA0-DA0/dao-dao-ui/assets/521978/adbdba77-dcef-4e06-8af5-15fdaa187523)

**Comment by JakeHartnell** [comment]
![image](https://github.com/DA0-DA0/dao-dao-ui/assets/521978/0015c9a7-0b23-4083-8541-37785c2e90ba)

**Comment by JakeHartnell** [comment]
Haven't been able to get the veto button working on a proposal page...
![image](https://github.com/DA0-DA0/dao-dao-ui/assets/521978/d6637791-9d32-4b4d-8127-e593d08d42fd)

**Comment by JakeHartnell** [comment]
> Haven't been able to get the veto button working on a proposal page... ![image](https://private-user-images.githubusercontent.com/521978/292029072-d6637791-9d32-4b4d-8127-e593d08d42fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMDk3MjcsIm5iZiI6MTcwMzEwOTQyNywicGF0aCI6Ii81MjE5NzgvMjkyMDI5MDcyLWQ2NjM3NzkxLTlkMzItNGI0ZC04MTI3LWU1OTNkMDhkNDJmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQyMTU3MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lODE1MzYxMzhkMWM3ZmI5Mzk5OTk1MGI3OGJjZjYzMWFmMDVjODg2MDllMjYwNjEzYTNjMjVhNzhkNTA2ZjY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ojrEXSs1p8gMeJ-R8Ai3ZzONxobj9mFuZkh6WYdUnas)

Oh, think this is because I hadn't setup vetoable DAOs

**Comment by NoahSaso** [comment]
> > Haven't been able to get the veto button working on a proposal page... ![image](https://private-user-images.githubusercontent.com/521978/292029072-d6637791-9d32-4b4d-8127-e593d08d42fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMDk3MjcsIm5iZiI6MTcwMzEwOTQyNywicGF0aCI6Ii81MjE5NzgvMjkyMDI5MDcyLWQ2NjM3NzkxLTlkMzItNGI0ZC04MTI3LWU1OTNkMDhkNDJmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQyMTU3MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lODE1MzYxMzhkMWM3ZmI5Mzk5OTk1MGI3OGJjZjYzMWFmMDVjODg2MDllMjYwNjEzYTNjMjVhNzhkNTA2ZjY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ojrEXSs1p8gMeJ-R8Ai3ZzONxobj9mFuZkh6WYdUnas)
> 
> Oh, think this is because I hadn't setup vetoable DAOs

ah yes, but i'll fix it so that the action includes those not added

**Comment by NoahSaso** [comment]
Fixed these in:
- https://github.com/DA0-DA0/dao-dao-ui/pull/1537/commits/d996d92deb30cf64b34c5c1266b9129cd32f18b0
- https://github.com/DA0-DA0/dao-dao-ui/pull/1537/commits/59de163dcf2176633640ff2d66b5032f280a546c
