### ISSUE TITLE
Can't remove a SubDAO without adding one

### ISSUE THREAD

**Issue by JakeHartnell** [DA0-DA0/dao-dao-ui#1545]
![image](https://github.com/DA0-DA0/dao-dao-ui/assets/521978/f377654d-8891-4f39-acdb-34cca75912d2)

**Comment by NoahSaso** [comment]
can you try resetting the proposal and try again? there have been cases of that `Please correct the errors above.` error being caused by stuck errors, and it is more likely it's that than this action breaking. big doubt
