### ISSUE TITLE
No Upload WASM as described in docs

### ISSUE THREAD

**Issue by gluax** [DA0-DA0/dao-dao-ui#1586]
https://docs.daodao.zone/docs/recipes/contract-deployment Lists that the DAO should be able to upload a contract.

However, when I look at the smart contracting section(and all the other sections) I see no way to upload a contract. I do see instantiation, though.

![image](https://github.com/DA0-DA0/dao-dao-ui/assets/16431709/9bd103e9-1a84-4fe3-b3ba-2281109a40ee)

How can one upload a smart contract?

**Comment by NoahSaso** [comment]
I think the docs are referring to instantiating a smart contract, not uploading a new code ID. Unfortunately, the gas limit on smart contract executions makes it difficult for a smart contract to upload another smart contract (I believe our proposal modules restrict a proposal's metadata, including its messages, to 30KB).

I just made a PR (https://github.com/DA0-DA0/dao-dao-ui/pull/1593) to add an upload smart contract action, but it will only work in the wallet page (daodao.zone/me/tx) and in chain governance proposals for now.
