### ISSUE TITLE
Centering of the description text

### ISSUE THREAD

**Issue by mOdeToken** [DA0-DA0/dao-dao-ui#1675]
Not exactly an issue, but I suggest adjusting the text alignment of the DAO description to be centered, consistent with every other detail on the Home page of the created DAO. Currently, the misalignment of the text, being the sole non-centered element, presents a slightly odd appearance. Addressing this minor detail would enhance the overall aesthetics and professionalism of the UI, I think.

![image](https://github.com/DA0-DA0/dao-dao-ui/assets/101747355/721c95f9-4134-40f9-9036-773d3de15c92)

**Comment by JakeHartnell** [comment]
We're going to tackle this in the redesign! https://github.com/DA0-DA0/dao-dao-ui/pull/1678

Let us know if you have feedback on the new designs, closing this for now.
