### ISSUE TITLE
DAO name spacing overlap

### ISSUE THREAD

**Issue by CLHRAE** [DA0-DA0/dao-dao-ui#1699]
I just noticed this in a video I was editing.  

Have a look at the Best Vibes admin subDAO name overlapping the "card next door".

<img width="365" alt="Screenshot 2024-02-09 at 13 30 34" src="https://github.com/DA0-DA0/dao-dao-ui/assets/114192151/d4968e19-1afa-43bc-909d-087e1e214c95">

**Comment by noahsaso** [comment]
hm i fixed this yesterday. can you try reloading the page?

**Comment by CLHRAE** [comment]
Screenshot was from a video I made yesterday, so it's probably fixed.  I'll re-open the issue if it pops up again.
