### ISSUE TITLE
Loading new Migaloo proposal 

### ISSUE THREAD

**Issue by CLHRAE** [DA0-DA0/dao-dao-ui#1701]
I noticed on migaloo.explorers.guru that Migaloo have a proposal open 23.
On the explorer the title displays as "Enable wBTC Restaking"
When trying to load the proposal through DAO DAO, it displays the following.   I have not created the proposal, as it didn't look right.  

Further, the code to execute looks pretty suspect as well. 

Note: I troubleshot with an Osmosis proposal, which seems to be loading correctly.

<img width="889" alt="Screenshot 2024-02-12 at 10 51 39" src="https://github.com/DA0-DA0/dao-dao-ui/assets/114192151/b080a4d9-241a-460f-812d-1744e7adffde">

**Comment by noahsaso** [comment]
Yeah, whenever you see a proposal like this with the title matching the raw data type, it's because our frontend doesn't have the message type loaded. Will add it.

**Comment by CLHRAE** [comment]
The title is still the same, but the code seems to have updated.  

<img width="871" alt="Screenshot 2024-02-13 at 11 32 58" src="https://github.com/DA0-DA0/dao-dao-ui/assets/114192151/2f666052-c8cc-412a-9467-d4983679af90">

**Comment by noahsaso** [comment]
> The title is still the same, but the code seems to have updated.
> 
> <img alt="Screenshot 2024-02-13 at 11 32 58" width="871" src="https://private-user-images.githubusercontent.com/114192151/304393272-2f666052-c8cc-412a-9467-d4983679af90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5NDc0NDMsIm5iZiI6MTcwNzk0NzE0MywicGF0aCI6Ii8xMTQxOTIxNTEvMzA0MzkzMjcyLTJmNjY2MDUyLWM4Y2MtNDEyYS05NDY3LWQ0OTgzNjc5YWY5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNFQyMTQ1NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NjdiNzUzNzYzZTM3NDQ3ZDAwYTM4NzNiM2QwYjBkZTNlODg3NmU0NTRlZmNhMzMxMDk5YmYzZDU4MGEzZmJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MPCPmMTmz2GDHmIsPdXyzGQ8BRE3-Un7eP-dn5Rl4VM">

oh damn yeah, nice. fixed now for real :)

<img width="1140" alt="Screenshot 2024-02-14 at 13 46 08" src="https://github.com/DA0-DA0/dao-dao-ui/assets/6721426/bdb755d0-05ff-4471-b80e-db6a823b8c72">
