### ISSUE TITLE
Vesting widget not showing after creating vesting contract manager.

### ISSUE THREAD

**Issue by Dizz02** [DA0-DA0/dao-dao-ui#1706]
There are no vesting contracts that can be cancelled as i try to create new vesting params.

**Comment by Dizz02** [comment]
![Screenshot (613)](https://github.com/DA0-DA0/dao-dao-ui/assets/83427844/f9ee0d47-7e55-4d13-8c74-448c763539a8)

**Comment by noahsaso** [comment]
ah you first have to pass a proposal that enables it, and then you will be able to create new vesting payments!
