### ISSUE TITLE
Show staked assets, that are staked to other DAO's

### ISSUE THREAD

**Issue by mOdeToken** [DA0-DA0/dao-dao-ui#1723]
In the Treasury of every DAO you are able to see all the assets you manage and also where are they staked. Is it possible to make it so that you could also see assets that are staked on other DAOs?

For example we have a separate DAO structure - Nearchos, that holds some $KLEO tokens. We have staked those tokens on Kleomedes DAO and now the treasury simply says that we own 0 $KLEO, even tho they are staked on DAO DAO.

**Comment by noahsaso** [comment]
that's a bug, it should be showing your $KLEO stake :0
thanks for submitting this!

**Comment by noahsaso** [comment]
fixed!

this was actually due to Kleomedes using a different code ID of our cw20 staking voting module: `1495`. how dare they 😠
