### ISSUE TITLE
Add Kleomedes Dashboard to dApps list

### ISSUE THREAD

**Issue by mOdeToken** [DA0-DA0/dao-dao-ui#1724]
Our dashboard dApp is created to claim monthly rewards and check your claiming stats.

Claiming is for people/DAOs who are staking $KLEO or delegating any assets for our Validator.

I understand that this is a dApp for quite narrow circle of people (on the other hand we have almost 40k delegators), but maybe it would be able to make it visible for those DAOs which hold/stake $KLEO and/or stake any assets to our Validator?

On the other hand if it could be visible for everyone it could give us a certain advantage, but that's just an idea, I fully understand if it will not be fulfilled 🙂

Thanks!

**Comment by noahsaso** [comment]
Happy to add it :)
Resolved by 3fefb4d0a3ba47fb766c804ed402e77fa8a9c702
