### ISSUE TITLE
Option to hide voting outcome until proposal is over

### ISSUE THREAD

**Issue by noahsaso** [DA0-DA0/dao-dao-ui#1729]
Flarnrules [asked in the Discord](https://discord.com/channels/895922260047720449/895926354728603659/1212061587272376412):

> Any chance that there is a feature (or this feature is being worked on) for private voting until the proposal is over, similar to Shutter? See this tweet by the bankless guy for an example:
> 
> https://twitter.com/raybankless/status/1762445195562377347?s=19

**Comment by JakeHartnell** [comment]
Problem with this is all the data is still on chain, anyone who knows how to do a smart contract info could get the current results.

We definitely should work on proper privacy features. MACI is probably the way to go: https://maci.pse.dev/

https://github.com/DoraFactory/cosmwasm-maci/tree/main
