### ISSUE TITLE
Token metadata missing even though present in Skip API

### ISSUE THREAD

**Issue by noahsaso** [DA0-DA0/dao-dao-ui#1741]
Reported by Kaku in Discord: https://discord.com/channels/895922260047720449/895926354728603659/1214223616229646416

`factory/osmo1vdvnznwg597qngrq9mnfcfk0am9jdc9y446jewhcqdreqz4r75xq5j5zvy/ymos` is not loading from the Skip API. It should be showing up in https://daodao.zone/dao/osmo19umqdz6e4g0jamtw0ksnut7r225el5ckp5p7vchu6gw3fpyd62tsvwrzp3/treasury, but it's not.

It seems to be returned from Snapper, so it should be loaded: https://snapper.daodao.zone/q/skip-asset?chainId=osmosis-1&denom=factory/osmo1vdvnznwg597qngrq9mnfcfk0am9jdc9y446jewhcqdreqz4r75xq5j5zvy/ymos

**Comment by NoahSaso** [comment]
i think it was just a caching issue

**Comment by noahsaso** [comment]
i think it was just a caching issue
