### ISSUE TITLE
Show more following DAOs in sidebar

### ISSUE THREAD

**Issue by JakeHartnell** [DA0-DA0/dao-dao-ui#1774]
Can only see two DAOs in the following section of the sidebar even though there is tons of room.⁩ Following 6 DAOs currently.

<img width="343" alt="image" src="https://github.com/DA0-DA0/dao-dao-ui/assets/521978/893289a5-40b0-4b82-8b45-e0f2f768a5fd">

Also seems to happen in collapsed mode too.

<img width="94" alt="image" src="https://github.com/DA0-DA0/dao-dao-ui/assets/521978/46b722d3-620b-45b6-ada6-3d9903a6621d">

**Comment by noahsaso** [comment]
Completed by 34978af9f296d7b75c62b85128c90ee735cfb1cc
