### ISSUE TITLE
Indicating content availability in the scroller

### ISSUE THREAD

**Issue by nikitatrifan** [DA0-DA0/dao-dao-ui#1781]
Shadows in scrollers typically indicate there's more content to peek through

When you're at the start you can't really peek through to the left. All the content on this side is visible

Same applies to the other direction:

https://github.com/DA0-DA0/dao-dao-ui/assets/11634956/aded89af-b5a0-444b-9748-24d5675d6066

**Comment by noahsaso** [comment]
thanks for catching this! fixed in b480b571461b89de24d64b5890f22a4cfe19f06e

**Comment by nikitatrifan** [comment]
Fuego 🔥
