### ISSUE TITLE
UI is not updating transferred vesting payments

### ISSUE THREAD

**Issue by kopeboy** [DA0-DA0/dao-dao-ui#1786]
DAODAO UI is not updating the list of vesting contracts on the **Vesting Payments** tab according to the current admin after a transfer. For example:
- Core 1 SubDAO [still shows](https://daodao.zone/dao/juno1j6glql3xmrcnga0gytecsucq3kd88jexxamxg3yn2xnqhunyvflqr7lxx3/vesting) 4 contracts that were [transferred](https://daodao.zone/dao/juno1j6glql3xmrcnga0gytecsucq3kd88jexxamxg3yn2xnqhunyvflqr7lxx3/proposals/A43) to Development Department.
- Communications Department is still [not showing](https://daodao.zone/dao/juno1n34v729jqgysm5w0unukpt4kvqu4wqyacsv4krmd40f7pz5ruzwqau7e6m/vesting) 1 contract that was [transferred](https://daodao.zone/dao/juno1gyjl26rnqqyk6cuh6nqtvx8t885jgqagusvpqpvtgaygcjg2wjdqz0rzle/proposals/A11) from Development Department.

You can confirm with a query like this: `junod q wasm c juno1ajs39qk0kd5xcjc8lvsym9q9g8q5jalzreum7nwqg036mqrw7utqf9gsu4` 
This contract was transferred from Core 1 to Dev Dept to Comms Dept, but its showing on Core 1 & Dev Dept, not on Comms Dept (the only, real admin).

@NoahSaso already told me on [Discord](https://discord.com/channels/895922260047720449/1166541380869423184/1249381575683211337) that 
> this has to do with how vesting contracts are created and listed (through a factory contract), but it's not the most intuitive and we did not prepare it to automatically work for transfers

Even before a fix can make this automatic, I would like to know the manual way, if it exists, to correctly update what's shown on each DAO, especially considering we are talking about compensation of elected delegates, paid by the community of Juno users, who are also the biggest shareholders of DA0-DA0 and are instructed to use it in their (trial period) [Charter](https://hackmd.io/@G2q75faESMyRkexdnhUCpA/B1NPVxxRh#Section-IV3-%E2%80%94-Decisions-and-Actions).

**Comment by noahsaso** [comment]
thank you for reporting this! i finally got to this and it should be fixed in 0f43901c2ebbc130e6ca4ed54d13b47a5f2885ba
