### ISSUE TITLE
home feed proposal navigation multiple chains

### ISSUE THREAD

**Issue by Trigs-0** [DA0-DA0/dao-dao-ui#1789]
If you follow multiple chains so active proposals show up in your home feed, when you try to navigate to one from a different chain it doesn't automatically switch to that chain. 

Instead it just takes you to the chain page you're currently connected to with the same number proposal in the URL (if it exists). You have to manually navigate to the chain's page and then click on the proposal.

**Comment by noahsaso** [comment]
nice find, thanks! fixed by fa5fcac882ace9d46981d5353d09dc5cc8f9ed91
