### ISSUE TITLE
Inaccurate migrate warning

### ISSUE THREAD

**Issue by ismellike** [DA0-DA0/dao-dao-ui#1796]
Migrate messages are incorrectly saying that the DAO is not the owner of the specified contract. (msg was successfully executed)

![image](https://github.com/DA0-DA0/dao-dao-ui/assets/5104272/0d12f670-cf10-440d-ab1b-fda528ce354f)

**Comment by noahsaso** [comment]
thanks! fixed by de82154d6366541db245b8f7994b3d54f7ec43f0
