### ISSUE TITLE
Profile pic upload modal incorrectly placed behind Logged in confirmation modal

### ISSUE THREAD

**Issue by pageofswrds** [DA0-DA0/dao-dao-ui#1798]
When the edit button is clicked, the modal is place underneath (and is inaccessible, until the first one is closed). Beyond this bug, there is room to reconsider the log-in flow as a whole (will elaborate on a later date)

![image](https://github.com/DA0-DA0/dao-dao-ui/assets/21699112/0a9b3d9d-7681-4848-9bb2-9e70d2863fc5)

**Comment by noahsaso** [comment]
nice catch 🙏 fixed in 79d65b7dd7f890f4141b7419ac611011a25f5a4e
