### ISSUE TITLE
Unstaking Proposal doesn't display amount

### ISSUE THREAD

**Issue by Trigs-0** [DA0-DA0/dao-dao-ui#1816]
When voting on a proposal to unstake tokens, it just displays 0 as the amount, instead of the amount chosen in the proposal creation process.

Users voting don't know how much they are voting to unstake.

![image](https://github.com/user-attachments/assets/b2058f24-9f43-4e8a-87de-a404f6b92eb6)

**Comment by noahsaso** [comment]
thank you! fixed in 3e89da3feede78d7775c4eca8625177bc5f169d7
