### ISSUE TITLE
Display social links for DAO/multisig

### ISSUE THREAD

**Issue by elsehow** [DA0-DA0/dao-dao-ui#236]
DAOs should be able to show social links. For example, a DAO may have a website, Discord or Twitter it wants to link to.

Implementation-wise, we may want to use [whoami](https://github.com/envoylabs/whoami/). We can wrap a UI for creating a whoami NFT in the DAO/multisig creation page. DAOs/multisigs can simply hold this NFT in their treasury.

For UX design: [see the metadata that whoami supports](https://github.com/envoylabs/whoami/). 

(Down the line, perhaps these could be a solution for DAO images - #185).

**Comment by JakeHartnell** [comment]
Closing in favor of: #1172
