### ISSUE TITLE
UI for depositing token into DAO

### ISSUE THREAD

**Issue by elsehow** [DA0-DA0/dao-dao-ui#293]
There are lots of addresses visible, and it's tempting to send tokens to the "governance address" thinking that's where you're treasury is (happened to a user).

I suggest we:
- Hide addresses other than the DAO address (must click on something to view them)
- Rename "DAO address" to "Treasury address" to make it clearer that you can send tokens there.

**Comment by NoahSaso** [comment]
Completed in v2.

![image](https://user-images.githubusercontent.com/6721426/199615028-64cb3c61-74df-4ad6-803b-1492cdac7f4e.png)
![image](https://user-images.githubusercontent.com/6721426/199615037-ce3606d5-e324-41d4-a205-f53d568da966.png)
