### ISSUE TITLE
Tutorial modal for setting up Keplr and getting Juno.

### ISSUE THREAD

**Issue by 0xekez** [DA0-DA0/dao-dao-ui#481]
If a user visits DAO DAO not being familiar with Cosmos or Juno the webpage is confusing. We should fix that.

Let's make a modal with @caseorganic's [tutorial](https://www.youtube.com/watch?v=jN-ns9lu6O0) about setting up Keplr and getting Juno. The connect wallet modal and all of the keplr related modals should have a help link which pops this up.

**Comment by JakeHartnell** [comment]
Going to close this, not because I don't think this is a good idea, but that at the current stage I think this is best served by video content.
