### ISSUE TITLE
Support a delegate selection UI

### ISSUE THREAD

**Issue by elsehow** [DA0-DA0/dao-dao-ui#576]
Optimism Gateway has a fantastic delegate selection UI. The idea is to allow DAO members to represent their attitudes and interests, then display those delegates so that people can make informed choices about whom they want to delegate to.

![Screenshot_from_2022-06-01_15-22-23](https://user-images.githubusercontent.com/7132461/171511726-7198abf7-52bc-4c60-90ca-332516c12048.png)

In practice, I imagine this will require a few things:
- The ability for delegates to describe themselves on-chain (and modify their descriptions).
- A way to query for everyone who has a description set.
- A UI for displaying these prospective delegates, and delegating one's vote to them.

Some initial thoughts:
- Perhaps you should be required to set a description in order to make yourself available for delegations. Aside form making people do the least to make a case for themselves, making "prospective delegate" status explicit has the initial benefit making queries more straightforward (delegates would be a subset of all DAO members).
- Perhaps this could be integrated with the "register to vote" UI. you might be prompted to register and delegate in a single step. For this, the delegates could be listed at the top, with a button below everyone's profile that says, "I want to vote on governance proposals directly."

**Comment by JakeHartnell** [comment]
This is great! But we need to do contracts and can't work on it until then. : (

Closing for now.
