### ISSUE TITLE
Create a 'constitution'

### ISSUE THREAD

**Issue by elsehow** [DA0-DA0/dao-dao-ui#577]
Optimism Collective has a [constitution](https://app.optimism.io/airdrop/constitution). Constitutions are a great way to set norms, values, and expectations around DAO governance.

The DAO DAO DAO should have a constitution that specifies DAO DAO's role in the DAO DAO ecosystem and communicates our unique values and philosophy. 

From the implementation perspective, the constitution would effectively a UI feature special to the DAO DAO dapp. We can offer this example as a pattern for SDAs to follow.

**Comment by NoahSaso** [comment]
We will probably revisit this when demand is higher. Or alternatively create some proposal pinning system.

Markdown proposal descriptions are sufficient for creating constitutions for now.
