### ISSUE TITLE
Proposal Timestamps: Summary and Detail views

### ISSUE THREAD

**Issue by TrevorJTClarke** [DA0-DA0/dao-dao-ui#581]
As a user/DAO participant, I want to see proposal timestamps that reflect when the latest action has taken place.
It is critical for me to understand **when** a proposal was passed, executed, etc. The context of proposals gets lost without point in time.

### Problems:
- Current proposals do not have time visible in relation to each proposal in a list or in the proposal detail view.
- Missing timestamps break coordination on time-sensitive proposal types
- Missing timestamps break context for off-chain governance posts

### Requirements:
1. Implement timestamps into the proposal schema: https://github.com/DA0-DA0/dao-contracts/issues/343
2. Add a subtle but useful simple UI element to display when a proposal took place, ideally near wherever the TXN hash is displayed as the context is the same.

### References:

**List view - no timestamps**
<img width="798" alt="Screen Shot 2022-06-07 at 10 26 52 AM" src="https://user-images.githubusercontent.com/2633184/172445517-ae21852f-a807-40d6-9c1e-14edcf93b098.png">

**Detail view - no timestamps**
<img width="1198" alt="Screen Shot 2022-06-07 at 10 27 05 AM" src="https://user-images.githubusercontent.com/2633184/172445536-913ade81-165a-44fb-975a-3c9179a7eba1.png">

**Comment by NoahSaso** [comment]
Completed in v2.
