### ISSUE TITLE
Add staked token amounts to treasury summary

### ISSUE THREAD

**Issue by TrevorJTClarke** [DA0-DA0/dao-dao-ui#582]
Needs to be a simple way to understand how much a DAO has staked, so when a DAO stakes it doesn't look like the tokens are... GONE.

When I setup the original staking messages, i also tried to include this total, however it appeared the version of cosmjs (stargate) was missing the needed RPC methods. This should be fixed now, or is easy to add now.

**Comment by blue-note** [comment]
glad you created this, I was just thinking about this!

**Comment by NoahSaso** [comment]
Completed in v2.

**Comment by TrevorJTClarke** [comment]
> Completed in v2.

HELL YEAH!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

that is all.
Cheers 😻
