### ISSUE TITLE
Validate that proposal is within size constraints

### ISSUE THREAD

**Issue by elsehow** [DA0-DA0/dao-dao-ui#717]
In creating a proposal with a long body, the chain says:

```
failed to execute message; message index: 0: Proposal is (54719) bytes, must be <= (30000) bytes: execute wasm contract failed: invalid request
```

If we are able to check the byte size of proposals in real-time, it would be nice to warn users that their proposal is too big in the frontend.

**Comment by NoahSaso** [comment]
Should we close this @elsehow @0xekez? It hasn't come up much...

**Comment by JakeHartnell** [comment]
Closing...
