### ISSUE TITLE
JunoSwap Actions

### ISSUE THREAD

**Issue by JakeHartnell** [DA0-DA0/dao-dao-ui#718]
Ok! Time has come to start adding actions for other projects and protocols! May need to update our design a bit to support these because there will be many (especially with ICA).

JunoSwap is a good place to start. Some actions I would like to do as a DAO:
- Create a pool
- Add / remove liquidity from a pool
- Swap a token in a pool
- Add external incentives to a pool

@ben2x4 or @sashimi36, any other suggestions here?

**Comment by onivalidator** [comment]
The MetaRat DAODAO wanted to be able to do somethings along these lines.

Their biggest mentions were being able to stake numerous assets. But also LPing in pools on Junoswap. They have quite a bit of USDC and are looking to grow their treasury. Perhaps the ability to reinvest those rewards automatically, without having to issue a vote each time as well?

**Comment by JakeHartnell** [comment]
Many elements from the swap template can probably be reused for other DEXs if we.

**Comment by stephenreid321** [comment]
Any news on this? I would love to be able to easily create a liquidity pool for a token created on DAODAO.

**Comment by stephenreid321** [comment]
Ooh, does label 'action' mean this is being worked on? 🤗

**Comment by ezekiiel** [comment]
@stephenreid321 this isn't on our immediate list of priorities. if someone wanted to take it on though, we have docs about how to add an action to the ui :) https://github.com/DA0-DA0/dao-dao-ui/wiki/Adding-an-action-to-DAO-DAO

**Comment by JakeHartnell** [comment]
RIP... closing until Wynd / Osmosis.
