### ISSUE TITLE
Show Execute in proposal view

### ISSUE THREAD

**Issue by elsehow** [DA0-DA0/dao-dao-ui#719]
In `dapp/dao/[address]`, the list of proposals could stand to show an "Execute" button if the proposal needs to be executed.

Consider: I cannot see which of these need to be executed.

![Screenshot from 2022-07-12 14-30-46](https://user-images.githubusercontent.com/7132461/178599103-d1e80453-e2fc-4385-9259-619740c4cb50.png)

I should be able to execute these right from this view if I need to.

**Comment by NoahSaso** [comment]
All passed proposals need to be executed. Technically, passed proposals with no actions don't *need* to be executed, but in the case of deposits being returned, even action-less proposals need to be executed. I'm not sure if an execute button would be worth the clutter.

**Comment by JakeHartnell** [comment]
Agree with Noah here.
