### ISSUE TITLE
Treasury History list rework suggestion

### ISSUE THREAD

**Issue by onewhiskeypls** [DA0-DA0/dao-dao-ui#810]
We should rework the treasury history to either:

- include pagination
- change to a collapsed view with a "expand and show all" button
- change to a condensed scrollview

**Comment by NoahSaso** [comment]
Added pagination in #811 

Does that PR seem satisfactory?

**Comment by onewhiskeypls** [comment]
@NoahSaso it would be, but i see a couple of issues :) will ping you elsewhere

**Comment by JakeHartnell** [comment]
Closing as stale. Feel free to reopen with more context if you think it's still relevant.
