### ISSUE TITLE
treasury history should track a dao's gov token in txs

### ISSUE THREAD

**Issue by onewhiskeypls** [DA0-DA0/dao-dao-ui#812]
see: [neta dao](https://daodao.zone/dao/juno1c5v6jkmre5xa9vf9aas6yxewc7aqmjy0rlkkyk4d88pnwuhclyhsrhhns6). it has had $NETA donations, but they are not tracked in the tx history

**Comment by NoahSaso** [comment]
This needs a treasury indexer to work correctly.

**Comment by JakeHartnell** [comment]
Closing a stale, feel other issues cover tx history.

**Comment by JakeHartnell** [comment]
Related: #228
