### ISSUE TITLE
add non-voting members to member based DAO

### ISSUE THREAD

**Issue by nullmames** [DA0-DA0/dao-dao-ui#815]
Add non-voting members, i.e members with no voting weight to member based dao's.

This will allow non elected, or org member with no vote to make proposals on behalf of the DAO. For example, an accountant can propose pay roll, or payments for services, etc.

Ideally, this would be a separate button that when clicked adds a form field under a new heading "non-voting member(s)". There should only be a field for member address, no voting weight field.

When the member list is displayed on the right hand column at the DAO home page, a separate heading should be added for non-voting member addresses.

**Comment by ezekiiel** [comment]
As a start, we could allow this in templates by removing the `validatePositive` field here: https://github.com/DA0-DA0/dao-dao-ui/blob/40f3cbfe676a98bf7b9db7b646e74e5b2dae4502/packages/voting-module-adapter/adapters/cw4-voting/actions/makeManageMembersAction/ManageMembersComponent.tsx#L92

Would be great to support this during creation as well. Should also be a small change. The contracts are happy with this. :)

**Comment by nullmames** [comment]
HI @ezekiiel, i had a quick look. IMO, still needs validation. There is already `validateNonNegative` available [here](https://github.com/DA0-DA0/dao-dao-ui/blob/b00f85f788195f3a1caf2aabf6ff5ba37289210b/packages/utils/validation/index.ts#L27).

https://github.com/DA0-DA0/dao-dao-ui/pull/821

**Comment by elsehow** [comment]
@nullmames Is this done?

**Comment by nullmames** [comment]
@elsehow I would say partially complete. Have changed the validation of voting weight to include 0 weight. Still could improve the ui

**Comment by NoahSaso** [comment]
I think validation is sufficient in this case. Adding additional UI to the manage members action or DAO creation flow will look cluttered and may confuse people who are less familiar with DAOs if they're presented with a voting or non-voting member choice. @nullmames is there anything specific you want to see?

**Comment by NoahSaso** [comment]
@0xekez https://github.com/DA0-DA0/dao-contracts/blob/main/contracts/proposal/cwd-proposal-single/src/contract.rs#L273-L278 it seems like non-voting members cannot do anything.

**Comment by nullmames** [comment]
I think this is fine to close in that case.
