### ISSUE TITLE
Add Emojis to Meta Embeds for Proposals

### ISSUE THREAD

**Issue by grubcowboy** [DA0-DA0/dao-dao-ui#832]
<img width="451" alt="Screen Shot 2022-08-18 at 4 19 45 PM" src="https://user-images.githubusercontent.com/51924762/185511623-af9cc9e4-5e30-4fc0-9d5b-9bff27528503.png">

would be awesome to support Emoji characters for meta text in embed.

also, minor nit, but would it be possible to remove the image alt-text for the embed. i think the proposal text alone would read better.

**Comment by JakeHartnell** [comment]
Unfortunately, I don't think there is anything we can do for this. We include the whole title field in [next-seo](https://github.com/garmeeh/next-seo), so the emojis are included, they just aren't rendered correctly in some contexts (like discord).

The alt text is also not explicitly included, but Discord shows it anyway.
