### ISSUE TITLE
Show dates when proposals start and end

### ISSUE THREAD

**Issue by elsehow** [DA0-DA0/dao-dao-ui#852]
From [this piece of Twitter feedback](https://twitter.com/soi2studio/status/1562475897357484033?s=21&t=nizEpRFfyhsXaO1qkEqNkg):

>  I might be missing something, but how do i see when a proposal starts and ends? And on the vote summary page it says 'completed' but the prop is still in the voting period. Bit confusing.

Not sure what the "completed" means - perhaps it means the person has already voted?

**Comment by NoahSaso** [comment]
The date now corresponds to the status in v2 thanks to the indexer work and redesign.
