### ISSUE TITLE
Frontend support for 'voting up until expiration time' 

### ISSUE THREAD

**Issue by blue-note** [DA0-DA0/dao-dao-ui#870]
We are adding contract feature that will allow voting up until a proposal has expired, even if its status has already changed to 'passed' or 'rejected.' This will allow more people to show support for the proposal and express their preference. We should support this in the frontend (allow voting if not expired even if status is Rejected / Passed), and there probably should also be language indicating that even though the status has changed, one can still vote (or something of that sort)

**Comment by 0xekez** [comment]
not going to land this as part of v2. will be a minor version after that :)
