### ISSUE TITLE
Simulate `Execute Smart Contract` action payloads to ensure json payload is valid

### ISSUE THREAD

**Issue by de-husk** [DA0-DA0/dao-dao-ui#873]
Whenever I write the json for the `Execute Smart Contract` actions, I often make a mistake and only find out about it when I fail to execute the proposal after it passes.

We should investigate how hard it would be to call the cosmos-sdk Simulate endpoint for the smart contract ExecuteMsg json against the configured contract address, to verify that the json is correct (without spending gas or actually executing the tx).

I think the cosmos-sdk still requires Simulate txs to be signed, but that requirement may have been lifted.

**Comment by de-husk** [comment]
Cosmos-SDK does not require the simulated transaction to be signed after all!

The cosmos-SDK is just building a RawTx with an empty sig for the simulate client flow:
https://github.com/cosmos/cosmos-sdk/blob/main/client/tx/tx.go#L133
https://github.com/cosmos/cosmos-sdk/blob/main/client/tx/factory.go#L359
https://github.com/cosmos/cosmos-sdk/blob/main/x/auth/tx/builder.go#L292

**Comment by 0xekez** [comment]
woah, cool!

**Comment by NoahSaso** [comment]
@de-husk We now simulate all proposal action payloads before submitting a proposal, which includes the execute smart contract actions! Yay 🎉
