### ISSUE TITLE
Image upload component

### ISSUE THREAD

**Issue by JakeHartnell** [DA0-DA0/dao-dao-ui#888]
Improve the existing image uploader component to upload an image to IPFS.

Personally, think NFT storage would work just fine for this: https://nft.storage/

https://www.figma.com/file/ZnQ4SMv8UUgKDZsR5YjVGH/Dao-2.0?node-id=3601%3A76877

![image](https://user-images.githubusercontent.com/521978/195731280-f0295441-c88e-43dc-a44e-24888db6c126.png)

**Comment by JakeHartnell** [comment]
@NoahSaso this could be related to the Mint NFT action? May be worth tackling at the same time?

**Comment by NoahSaso** [comment]
> @NoahSaso this could be related to the Mint NFT action? May be worth tackling at the same time?

Yup! This is part of #953
