### ISSUE TITLE
Allow voting up to expiration time

### ISSUE THREAD

**Issue by 0xekez** [DA0-DA0/dao-dao-ui#957]
https://github.com/DA0-DA0/dao-contracts/pull/477

in DAO DAO v2 we allow casting votes after the proposal has passed. this allows for more socially meaningful vote tallies as preferences can be stored on-chain even if the vote does not impact the proposal outcome (i.e. it has already passed or failed).

**Comment by NoahSaso** [comment]
Duplicate of #870
