### ISSUE TITLE
Remove Odyssean easter egg

### ISSUE THREAD

**Issue by elsehow** [DA0-DA0/dao-dao-ui#983]
![image](https://user-images.githubusercontent.com/7132461/211367380-3ec8fc96-ad8b-4c44-a489-f8e00468421c.png)

Clicking on "Nobody" makes this happen - cute, but inexcusably confusing. Clicking on "Nobody" should probably offer to connect a wallet instead.

**Comment by NoahSaso** [comment]
Resolved in #984
